   version: '3'
   services:
     api-gateway:
       build: ./api-gateway
       ports:
         - "3000:3000"
       environment:
         - USER_SERVICE_PORT=4000
         - TRIP_SERVICE_PORT=5000
         - DEMAND_SERVICE_PORT=6000
         - SUPPLY_SERVICE_PORT=7000
         - LOCATION_SERVICE_PORT=8000
         - NOTIFICATION_SERVICE_PORT=9000
         - PRICING_SERVICE_PORT=10000
         - ANALYTICS_SERVICE_PORT=110009